/**
 * Óï¾äÃû×Ö
 */
package parser;

/**
 * @author Qideas
 *
 */
public enum StatementName {

	PROGRAM,DECLARE_STM,ASSIGN_STM,BLOCK_STM,IF_STM,ELSE_STM,WHILE_STM,CONDITION_STM,READ_STM,WRITE_STM,EXPRESSION_STM,
	NUMBER_STM,VARIABLE_STM,CONDITION_SYMBOL,ADD_MINUS,TERM,MULTI_DIVID,FACTOR
}
